name: thread_clone
description: "A Flutter project for building threads."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

environment:
  sdk: ">=3.10.0-0 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # State management & storage
  get: ^4.7.3
  get_storage: ^2.1.1

  # Networking & backend
  supabase_flutter: ^2.12.0
  share_plus: ^12.0.1
  flutter_dotenv: ^6.0.0

  # Utilities
  uuid: ^4.5.2
  jiffy: ^6.4.4
  form_validator: ^2.1.1

  # Images & media
  image_picker: ^1.2.1
  flutter_image_compress: ^2.4.0
  extended_image: ^10.0.1

  # UI Enhancements
  shimmer: ^3.0.0
  custom_refresh_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# Flutter-specific settings
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  adaptive_icon_foreground: "#000000"